# Wiki Update Tracker, to track changes in wiki original pages, and update issues to report when a translation is required

name: Wiki Update Tracker

on:
  push:
    branches: [master]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Skip Tracking Steps?
        if: env.ENABLE != '1ENABLED'
        run: echo ENABLE_WUT Secret not set to 1ENABLED, skipping page tracking... 

      - name: Checkout git repository
        if: env.ENABLE == '1ENABLED'
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Get custom App JWT
        if: env.ENABLE == '1ENABLED'
        id: get_token
        uses: machine-learning-apps/actions-app-token@0.21
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Check original pages status and update translation Projects
        if: env.ENABLE == '1ENABLED'
        uses: Awagi/wiki-update-tracker@v1.8.0
        with:
          log-level: "DEBUG"
          repo-path: "."
          original: "wiki"
          translations: |-
            fr:wiki/fr
            ja:wiki/ja 
          filters: "**/*"
          ignores: |-
            wiki/LICENSE
          gen-stubs: |-
            *.md
          stub-template: .github/workflows/wut-templates/translation-stub-template.md
          gen-branch: wut-branch
          request-merge: true
          gen-copy: |-
            *.png
          token: ${{ steps.get_token.outputs.app_token }}
          instruct-projects: |-
            *.md
          project-title-template: "Wiki {t.translation.language} Update Tracker"
          project-description-template: "{t.translation.language} translation effort."
          project-card-create-template: .github/workflows/wut-templates/project-create-template.md
          project-card-initialize-template: .github/workflows/wut-templates/project-initialize-template.md
          project-card-update-template: .github/workflows/wut-templates/project-update-template.md
          project-card-uptodate-template: .github/workflows/wut-templates/project-uptodate-template.md
          project-card-orphan-template: .github/workflows/wut-templates/project-orphan-template.md
    env:
        ENABLE: ${{ secrets.ENABLE_WUT }}
